### ISSUE TITLE
Files not generated and file access denied

### ISSUE THREAD

**Issue by RealPoke** [Explv/Explvs-AIO#33]
I am having a similar problem now, it's pretty much the same error. But I can't use the Recourse button nor the GE button, and it gives me permissions denied in console.
The thing is that the summery file doesn't even exist. The script has not created any files or folders at all.

When I compile with Intellij the artifact is about 100MB less then when I compile with Eclipse and it crashes on start with the error that no tasks are found and the UI can't be loaded.
So I am compiling with Eclipse for now.

Might be related to #19 ?

OS: `Arch Linux`
Kernal: `x86_64 Linux 4.20.0-arch1-1-ARCH`

UPDATE: I don't think it has anything to do with permissions, but more so that it never generates the files. Since I can save/load just fine.

Log:
`[ERROR][01/11 02:57:16 AM]: Uncaught exception!
java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/martin/osbot/data/explv_aio_rsbuddy_summary.json" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.osbot.bB.checkPermission(im:19)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.File.exists(File.java:814)
	at org.aio.activities.grand_exchange.GrandExchangeHelper.getAllGEItems(GrandExchangeHelper.java:38)
	at org.aio.gui.task_panels.ResourceTaskPanel.<init>(ResourceTaskPanel.java:33)
	at org.aio.gui.task_panels.TaskPanelFactory.createTaskPanel(TaskPanelFactory.java:9)
	at org.aio.gui.Gui.addTask(Gui.java:245)
	at org.aio.gui.Gui.lambda$3(Gui.java:97)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.aio.gui.Gui.open(Gui.java:232)
	at org.aio.script.AIO.lambda$2(AIO.java:125)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by RealPoke** [comment]
This is related I think.
https://github.com/Explv/Explvs-AIO/issues/19#issuecomment-453372827

**Comment by Explv** [comment]
@RealPoke is your OSBot directory called `OSBot` or `osbot`? I think the linux file system is case sensitive so we may need to add some logic to account for that

**Comment by RealPoke** [comment]
Great point, Linux is case sensitive. I will look into it later today and see if I can come up with a fix! 👍

**Comment by MasterOfHash** [comment]
Mine is `OSBot` and I hit this same issue.

**Comment by RealPoke** [comment]
It was because Linux is case sensitive.
#36
